#161254622 Rate articles on Authors Heaven
andela/ah-orcas-frontend pull request #27
Opened 2018-12-18 15:49 UTC by wrotich

#### What does this PR do?
```This PR merges the rate article branch with develop ```
#### Description of Task to be completed?
```allow logged in users to rate articles on Authors Haven```
```allow users to view average rating of an article ```
```Redesign the view article UI```
#### How should this be manually tested?
```Clone this repository```
- git clone https://github.com/andela/ah-orcas-frontend.git
```Change the working directory to the project folder```
- cd ah-orcas-frontend
```Checkout to the appropriate branch```
- git checkout ft-rate-an-article-161254622
```Install the required dependencies and start the server```
- npm install
- npm start
```You should be able to see the star ratings when you view a single article, i.e. average rating. Also, you will be able to rate a given article provided you are logged in```
#### Any background context you want to provide?
```Having ratings on a given article helps in getting the statistics that can be useful when collecting data on which topic is loved by the users ```
#### What are the relevant pivotal tracker stories?
[#161254622](https://www.pivotaltracker.com/story/show/161254622)
#### Screenshots (if appropriate)
- (Will add)

#### Checklist:

- [X] My code follows the style guidelines of this project
- [ ] At least 2 people have reviewed my PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] My PR has one commit.

2018-12-19 18:42 UTC, wrotich commented on src/components/ArticleView/App.js
> +    const { results, rates } = this.props;
Resolved

2018-12-20 12:29 UTC, evamaina approved these changes
LGTM

2018-12-20 12:40 UTC, Gidraf approved these changes
LGTM

2018-12-20 12:48 UTC, TheSteelGuy requested changes

2018-12-20 12:48 UTC, TheSteelGuy commented on src/actions/articles.action.js
>  const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDUzMTQ4MTMsImlhdCI6MTU0NDcxMDAxMywiaWQiOjUxfQ.qB3oqQNnoeoYnaTRIp9h4TXAmARQLfUjVVZzUpjAfCw';
pass this token from the actual login

2018-12-20 15:30 UTC, TheSteelGuy approved these changes

2018-12-20 17:46 UTC, merged